version: "3.8"
services:
  opus-classical-ui:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - opusclassical-network
    env_file: .env
    ports:
      - "3000:3000"
networks:
  opusclassical-network:
    driver: bridge
