services:
  opus-classical-ui:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - opusclassical-network
    env_file: .env
    ports:
      - "3000:3000"
    restart: always

networks:
  opusclassical-network:
    driver: bridge
