name: test-and-lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"
      - run: bun i
      - run: bun test
      - run: bun run lint
